# Snowflake Configuration
snowflake:
  account: "your_account"
  user: "your_username"
  password: "your_password"
  warehouse: "COMPUTE_WH"
  database: "FINANCIAL_ML_DB"
  schema: "ML_PIPELINE"
  role: "ACCOUNTADMIN"

# Data Generation Settings
data_generation:
  num_clients: 50000
  num_events_per_client: 150
  date_range_days: 365
  seed: 42

# Model Configuration
models:
  pytorch:
    hidden_layers: [128, 64, 32]
    dropout_rate: 0.3
    learning_rate: 0.001
    batch_size: 256
    epochs: 50
  
  xgboost:
    max_depth: 6
    learning_rate: 0.1
    n_estimators: 100
    subsample: 0.8
  
  sklearn:
    random_state: 42
    test_size: 0.2

# Feature Store Configuration
features:
  recency_days: [7, 30, 90, 365]
  frequency_windows: [30, 90, 180]
  monetary_thresholds: [10000, 50000, 100000, 500000]

# Streaming Configuration
streaming:
  batch_size: 1000
  frequency_seconds: 30
  snowpipe_name: "MARKETING_EVENTS_PIPE"
