-- Feature Store Demo Queries
-- Run these in Snowflake to demonstrate your Feature Store

-- 1. Show Feature Store Schema Structure
SHOW SCHEMAS IN DATABASE FINANCIAL_ML_DB;

-- 2. Show Objects in Feature Store Schema
USE SCHEMA FINANCIAL_ML_DB.FINANCIAL_FEATURE_STORE;
SHOW TABLES;
SHOW VIEWS;

-- 3. Feature Store Metadata
SELECT * FROM FEATURE_METADATA;

-- 4. Feature Definitions (First 20)
SELECT 
    FEATURE_NAME,
    FEATURE_TYPE,
    FEATURE_DESCRIPTION
FROM FEATURE_DEFINITIONS
ORDER BY FEATURE_NAME
LIMIT 20;

-- 5. Feature Statistics
SELECT 
    FEATURE_DESCRIPTION,
    COUNT(*) as NUM_FEATURES
FROM FEATURE_DEFINITIONS
GROUP BY FEATURE_DESCRIPTION
ORDER BY NUM_FEATURES DESC;

-- 6. Sample Client Features
SELECT 
    CLIENT_ID,
    ENGAGEMENT_SCORE_30D,
    RETIREMENT_READINESS_SCORE,
    LIFECYCLE_STAGE,
    TOTAL_ASSETS_UNDER_MANAGEMENT,
    ANNUAL_INCOME
FROM CLIENT_FINANCIAL_FEATURES_V1
WHERE ENGAGEMENT_SCORE_30D > 0.8
ORDER BY TOTAL_ASSETS_UNDER_MANAGEMENT DESC
LIMIT 10;

-- 7. Feature Distributions
SELECT 
    AGE_SEGMENT,
    COUNT(*) as CLIENT_COUNT,
    AVG(ENGAGEMENT_SCORE_30D) as AVG_ENGAGEMENT,
    AVG(RETIREMENT_READINESS_SCORE) as AVG_READINESS
FROM CLIENT_FINANCIAL_FEATURES_V1
GROUP BY AGE_SEGMENT
ORDER BY AGE_SEGMENT;

-- 8. High-Value Client Features
SELECT 
    CLIENT_ID,
    AGE,
    ANNUAL_INCOME,
    CURRENT_401K_BALANCE,
    TOTAL_ASSETS_UNDER_MANAGEMENT,
    WEALTH_GROWTH_POTENTIAL,
    SERVICE_TIER_NUMERIC
FROM CLIENT_FINANCIAL_FEATURES_V1
WHERE WEALTH_GROWTH_POTENTIAL > 0.7
AND SERVICE_TIER_NUMERIC >= 3
ORDER BY TOTAL_ASSETS_UNDER_MANAGEMENT DESC
LIMIT 20;

-- 9. Engagement Patterns
SELECT 
    LIFECYCLE_STAGE,
    AVG(TOTAL_EVENTS_30D) as AVG_MONTHLY_EVENTS,
    AVG(EMAIL_CLICK_RATE_30D) as AVG_EMAIL_ENGAGEMENT,
    AVG(WEB_PREFERENCE_RATIO) as AVG_WEB_PREFERENCE,
    COUNT(*) as CLIENT_COUNT
FROM CLIENT_FINANCIAL_FEATURES_V1
GROUP BY LIFECYCLE_STAGE
ORDER BY AVG_MONTHLY_EVENTS DESC;

-- 10. Feature Store Summary
SELECT 
    'Total Clients' as METRIC,
    COUNT(DISTINCT CLIENT_ID) as VALUE
FROM CLIENT_FINANCIAL_FEATURES_V1
UNION ALL
SELECT 
    'Total Features' as METRIC,
    COUNT(*) as VALUE
FROM FEATURE_DEFINITIONS
UNION ALL
SELECT 
    'Feature Categories' as METRIC,
    COUNT(DISTINCT FEATURE_DESCRIPTION) as VALUE
FROM FEATURE_DEFINITIONS;
